[package]
name = "imagen"
version = "0.1.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]

[dependencies]
rand = "0.3.15"

[dependencies.image]
version = "0.14"
default-features = false
features = ["jpeg"]
